### ISSUE TITLE
FileNotFoundError in newest release

### ISSUE THREAD

**Issue by sammarston15** [Justintime50/dad-python#3]
### Current State
Getting the following error in my virtualenv when trying to create a random address with `dad_tool.random_address`. Uninstalling and reinstalling the `dad_tool` package seems to result in the same error.
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/smarston/.local/share/virtualenvs/python-oWvDs7ZO/lib/python3.9/site-packages/dad_tool/dad/src/addresses/united-states/ut-addresses.min.json'
```

I've viewed the `site-packages/dad_tool` folder on my machine and it seems I do not have `site-packages/dad_tool/dad`.
![image (1)](https://github.com/Justintime50/dad-python/assets/49851556/085fccc0-04ff-4d7f-ba34-fc1f950142b9)

### Expected State
Package should install the `dad` submodule to prevent the error

**Comment by Justintime50** [comment]
[Found the culprit](https://github.com/Justintime50/dad-python/commit/e113873a97c5910f37b03302dfe597fda8f8cb4e), the command to initialize the submodule was removed when switching from Makefile to Justfile in the releasing process so it never gets included.

This is fixed in https://github.com/Justintime50/dad-python/commit/bb6f68baece2f1294058eab6929165f873175ba5
